import type { ActivityEvent, Merchant, Rider } from "./types";

export const MOCK_RIDERS: Rider[] = [
  {
    id: "rider-1",
    name: "Juan dela Cruz",
    vehicle: "Motorcycle",
    phone: "0917 123 4587",
    plateNumber: "NDJ 2201",
    licenseNumber: "N01-24-556789",
    status: "online-available",
    currentSpeedKph: 0,
    batteryPercent: 82,
    municipality: "Imus",
    barangay: "Anabu I-A",
    todayDeliveries: 6,
    completedDeliveries: 6,
    currentEarnings: 480,
    acceptanceRatePercent: 96,
    assignedOrderIds: [],
    walletBalance: 1250,
    x: 28,
    y: 34,
  },
  {
    id: "rider-2",
    name: "Maria Santos",
    vehicle: "Motorcycle",
    phone: "0918 456 2290",
    plateNumber: "NDK 5578",
    licenseNumber: "N01-23-441203",
    status: "online-delivering",
    currentSpeedKph: 32,
    batteryPercent: 54,
    municipality: "Imus",
    barangay: "Malagasang I-G",
    todayDeliveries: 9,
    completedDeliveries: 8,
    currentEarnings: 720,
    acceptanceRatePercent: 91,
    assignedOrderIds: ["order-1044"],
    walletBalance: 2140,
    x: 52,
    y: 58,
  },
  {
    id: "rider-3",
    name: "Pedro Reyes",
    vehicle: "Bicycle",
    phone: "0928 774 1132",
    plateNumber: "N/A",
    licenseNumber: "N01-25-118820",
    status: "barangay-dedicated",
    currentSpeedKph: 12,
    batteryPercent: null,
    municipality: "Kawit",
    barangay: "Poblacion IV",
    todayDeliveries: 4,
    completedDeliveries: 4,
    currentEarnings: 260,
    acceptanceRatePercent: 100,
    assignedOrderIds: [],
    walletBalance: 890,
    x: 68,
    y: 22,
  },
  {
    id: "rider-4",
    name: "Ana Lim",
    vehicle: "Motorcycle",
    phone: "0906 332 8871",
    plateNumber: "NDL 8834",
    licenseNumber: "N01-22-990147",
    status: "offline",
    currentSpeedKph: 0,
    batteryPercent: 0,
    municipality: "Imus",
    barangay: "Bucandala I",
    todayDeliveries: 0,
    completedDeliveries: 0,
    currentEarnings: 0,
    acceptanceRatePercent: 88,
    assignedOrderIds: [],
    walletBalance: 430,
    x: 40,
    y: 76,
  },
  {
    id: "rider-5",
    name: "Carlo Mendoza",
    vehicle: "Motorcycle",
    phone: "0995 213 6640",
    plateNumber: "NDM 1190",
    licenseNumber: "N01-24-772561",
    status: "emergency",
    currentSpeedKph: 0,
    batteryPercent: 21,
    municipality: "Cavite City",
    barangay: "Tejero",
    todayDeliveries: 3,
    completedDeliveries: 2,
    currentEarnings: 190,
    acceptanceRatePercent: 79,
    assignedOrderIds: ["order-1039"],
    walletBalance: 310,
    x: 80,
    y: 48,
  },
];

export const MOCK_MERCHANTS: Merchant[] = [
  {
    id: "merchant-1",
    storeName: "Amy's Carinderia",
    merchantName: "Amy Villanueva",
    merchantId: "MID-00142",
    phone: "0917 802 3345",
    category: "Food",
    status: "open",
    openHours: "6:00 AM - 8:00 PM",
    ordersToday: 42,
    completedOrdersToday: 37,
    cancelledOrdersToday: 0,
    pendingOrders: 2,
    preparingOrders: 3,
    readyForPickupOrders: 2,
    avgPrepTimeMinutes: 14,
    rating: 4.9,
    walletBalance: 6200,
    revenueToday: 12540,
    commissionToday: 1881,
    currentVoucherCampaign: "₱50 off first order",
    onlineStaffCount: 2,
    municipality: "Imus",
    barangay: "Anabu I-A",
    lastActivity: "2 min ago",
    x: 30,
    y: 40,
  },
  {
    id: "merchant-2",
    storeName: "Kawit Hardware Supply",
    merchantName: "Ricardo Manalo",
    merchantId: "MID-00098",
    phone: "0918 664 7723",
    category: "Hardware",
    status: "busy",
    openHours: "8:00 AM - 6:00 PM",
    ordersToday: 11,
    completedOrdersToday: 8,
    cancelledOrdersToday: 1,
    pendingOrders: 1,
    preparingOrders: 1,
    readyForPickupOrders: 1,
    avgPrepTimeMinutes: 22,
    rating: 4.6,
    walletBalance: 3100,
    revenueToday: 5400,
    commissionToday: 810,
    currentVoucherCampaign: null,
    onlineStaffCount: 1,
    municipality: "Kawit",
    barangay: "Poblacion IV",
    lastActivity: "9 min ago",
    x: 66,
    y: 25,
  },
  {
    id: "merchant-3",
    storeName: "Lancaster Fresh Mart",
    merchantName: "Grace Tan",
    merchantId: "MID-00211",
    phone: "0919 445 0021",
    category: "Marketplace",
    status: "open",
    openHours: "24 hours",
    ordersToday: 65,
    completedOrdersToday: 61,
    cancelledOrdersToday: 1,
    pendingOrders: 1,
    preparingOrders: 1,
    readyForPickupOrders: 1,
    avgPrepTimeMinutes: 9,
    rating: 4.8,
    walletBalance: 15200,
    revenueToday: 28900,
    commissionToday: 4335,
    currentVoucherCampaign: "10% off Marketplace",
    onlineStaffCount: 4,
    municipality: "Imus",
    barangay: "Malagasang I-G",
    lastActivity: "just now",
    x: 54,
    y: 60,
  },
  {
    id: "merchant-4",
    storeName: "Trias Auto Parts",
    merchantName: "Ferdinand Cruz",
    merchantId: "MID-00076",
    phone: "0920 118 8845",
    category: "Industrial",
    status: "closed",
    openHours: "8:00 AM - 5:00 PM",
    ordersToday: 0,
    completedOrdersToday: 0,
    cancelledOrdersToday: 0,
    pendingOrders: 0,
    preparingOrders: 0,
    readyForPickupOrders: 0,
    avgPrepTimeMinutes: 0,
    rating: 4.3,
    walletBalance: 900,
    revenueToday: 0,
    commissionToday: 0,
    currentVoucherCampaign: null,
    onlineStaffCount: 0,
    municipality: "Imus",
    barangay: "Bucandala I",
    lastActivity: "1 day ago",
    x: 42,
    y: 78,
  },
  {
    id: "merchant-5",
    storeName: "Tejero Home Services",
    merchantName: "Liza Ocampo",
    merchantId: "MID-00305",
    phone: "0921 556 9902",
    category: "Services",
    status: "paused",
    openHours: "9:00 AM - 7:00 PM",
    ordersToday: 3,
    completedOrdersToday: 2,
    cancelledOrdersToday: 1,
    pendingOrders: 0,
    preparingOrders: 0,
    readyForPickupOrders: 0,
    avgPrepTimeMinutes: 45,
    rating: 4.1,
    walletBalance: 1400,
    revenueToday: 800,
    commissionToday: 120,
    currentVoucherCampaign: null,
    onlineStaffCount: 1,
    municipality: "Cavite City",
    barangay: "Tejero",
    lastActivity: "38 min ago",
    x: 78,
    y: 50,
  },
];

export const MOCK_ACTIVITY: ActivityEvent[] = [
  { id: "evt-1", type: "new-order", message: "New order at Amy's Carinderia", timestamp: "just now" },
  { id: "evt-2", type: "delivery-started", message: "Maria Santos started delivery for order-1044", timestamp: "1 min ago" },
  { id: "evt-3", type: "merchant-opened", message: "Lancaster Fresh Mart opened", timestamp: "3 min ago" },
  { id: "evt-4", type: "rider-online", message: "Juan dela Cruz went online", timestamp: "5 min ago" },
  { id: "evt-5", type: "order-accepted", message: "Kawit Hardware Supply accepted order-1041", timestamp: "8 min ago" },
  { id: "evt-6", type: "voucher-redeemed", message: "Voucher redeemed at Lancaster Fresh Mart", timestamp: "12 min ago" },
  { id: "evt-7", type: "delivery-completed", message: "Pedro Reyes completed delivery order-1038", timestamp: "18 min ago" },
  { id: "evt-8", type: "order-cancelled", message: "Order cancelled at Tejero Home Services", timestamp: "22 min ago" },
  { id: "evt-9", type: "rider-offline", message: "Ana Lim went offline", timestamp: "30 min ago" },
  { id: "evt-10", type: "referral-registered", message: "New referral registered under Amy Villanueva", timestamp: "41 min ago" },
];
