import { useState } from "react";

export type SuperAdminModule = "admins" | "users" | "stores" | "catalog" | "engines" | "audit";

const MODULES: Record<SuperAdminModule, { eyebrow: string; title: string; description: string; actions: string[]; contract: string }> = {
  admins: { eyebrow: "IDENTITY & ACCESS", title: "Admin accounts", description: "Create Admin invitations, assign narrow permissions, suspend access, and review privileged sessions.", actions: ["Invite Admin", "Edit role permissions", "Suspend or restore Admin", "Review session history"], contract: "Admin identity, role, permission matrix, step-up access and audit endpoints" },
  users: { eyebrow: "PLATFORM CONTROL", title: "Users & roles", description: "Inspect accounts and perform audited account actions without exposing passwords or private wallet credentials.", actions: ["Create authorized account", "Edit allowed profile fields", "Suspend or restore access", "Assign server-approved capability"], contract: "User create/update/status/capability endpoints with field-level authorization" },
  stores: { eyebrow: "MARKETPLACE CONTROL", title: "Stores & merchants", description: "Create or correct merchant stores, branches, verification state, categories, and operating permissions.", actions: ["Add verified merchant", "Add store or branch", "Edit operating status", "Review merchant audit trail"], contract: "Merchant/store create, branch, verification, status and audit endpoints" },
  catalog: { eyebrow: "CATALOG CONTROL", title: "Products & listings", description: "Create or correct products, variants, services, auctions, and Pre-Loved listings using their separate workflows.", actions: ["Add product and variants", "Manage service listing", "Manage auction listing", "Manage Pre-Loved listing"], contract: "Separate Product, Service, Auction and Pre-Loved mutation contracts" },
  engines: { eyebrow: "COMMERCIAL CONTROL", title: "Formula & platform engines", description: "Version commission, markup, fees, incentives, delivery rules, feature flags, and effective dates.", actions: ["Create versioned rule", "Activate or retire rule", "Run server-side calculation test", "Apply audited manual override"], contract: "Formula rule, test, activation, override and immutable audit endpoints" },
  audit: { eyebrow: "SECURITY & COMPLIANCE", title: "Audit & recovery", description: "Review privileged changes, receipt issuance, exports, security events, errors, and recovery actions.", actions: ["Inspect immutable audit event", "Request secure export", "Review receipt issuance", "Start approved recovery action"], contract: "Audit read, secure export, receipt issuance and recovery authorization endpoints" },
};

export function SuperAdminModulePage({ module, previewMode = false }: { module: SuperAdminModule; previewMode?: boolean }) {
  const config = MODULES[module];
  const [visible, setVisible] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  return <div className="ecosystem-page super-admin-page">
    <header className="ecosystem-page-header"><div><span className="ecosystem-eyebrow">SUPER ADMIN · {config.eyebrow}</span><h1>{config.title}</h1><p>{config.description}</p></div><span className="super-admin-lock-state">{previewMode ? "PREVIEW MODE -- MOCK DATA" : "ACCESS NOT VERIFIED"}</span></header>
    {previewMode ? <section className="ecosystem-contract-panel" role="status"><div><span>DEMO PREVIEW -- NOT REAL ACCESS</span><h2>Showing the designed layout, not a live elevated session</h2><p>Clicking an action below just shows what it will do once Xano's Super Admin endpoints exist -- see docs/business/AdminEndpoints-Batch6.md for the full contract. Nothing here is wired to real data or capable of a real mutation.</p></div></section> : null}
    <section className="super-admin-action-grid">{config.actions.map((action, index) => <article key={action} style={previewMode ? { cursor: "pointer" } : undefined} onClick={previewMode ? () => setToast(`"${action}" is a preview only -- connects to Xano once ${config.contract.toLowerCase()} exist.`) : undefined}><span>PRIVILEGED ACTION {String(index + 1).padStart(2, "0")}</span><h2>{action}</h2><p>{previewMode ? "Preview only -- click to see what this connects to once Xano is wired." : "Hidden operational controls become active only after Xano returns this action in the current Super Admin capability set."}</p></article>)}</section>
    {toast ? <section className="ecosystem-contract-panel" role="status"><div><span>PREVIEW</span><p>{toast}</p></div><button type="button" onClick={() => setToast(null)}>Close</button></section> : null}
    {previewMode ? null : <section className="super-admin-disabled-action"><div><span>SERVER AUTHORIZATION REQUIRED</span><h2>No privileged action is active</h2><p>{config.contract}. Frontend visibility is never accepted as authorization.</p></div><button type="button" onClick={() => setVisible(true)}>Review access requirement</button></section>}
    {visible ? <section className="ecosystem-contract-panel" role="status"><div><span>GOD MODE INACTIVE</span><h2>{config.title} contract</h2><p>No data was created, edited, deleted, exported, or reclassified.</p></div><dl><div><dt>SESSION</dt><dd>Verified short-lived Super Admin elevation</dd></div><div><dt>PERMISSIONS</dt><dd>Server response lists allowed module actions</dd></div><div><dt>MUTATION</dt><dd>Every write rechecks authorization server-side</dd></div><div><dt>AUDIT</dt><dd>Actor, reason, old/new values, time and trace ID</dd></div></dl><button type="button" onClick={() => setVisible(false)}>Close</button></section> : null}
  </div>;
}
