import type { AuctionDetail, AuctionListing } from "../types/auction";

export const MOCK_AUCTIONS: AuctionListing[] = [
  {
    id: "auc-1",
    title: "Vintage Vinyl Record Player",
    category: "Electronics",
    sellerName: "Retro Finds PH",
    currentBid: 2450,
    minIncrement: 100,
    endsInLabel: "2h 14m left",
    bidderCount: 11,
    status: "ending-soon",
    isWatchlisted: true,
  },
  {
    id: "auc-2",
    title: "Handwoven Rattan Chair",
    category: "Home & Living",
    sellerName: "Cavite Crafts Co.",
    currentBid: 1800,
    minIncrement: 50,
    endsInLabel: "1d 4h left",
    bidderCount: 6,
    status: "live",
    isWatchlisted: false,
  },
  {
    id: "auc-3",
    title: "Limited Edition Sneakers (Size 9)",
    category: "Fashion",
    sellerName: "SoleTrade Manila",
    currentBid: 5200,
    minIncrement: 200,
    endsInLabel: "6h 40m left",
    bidderCount: 24,
    status: "live",
    isWatchlisted: true,
  },
  {
    id: "auc-4",
    title: "Restored Yamaha Guitar",
    category: "Other",
    sellerName: "Imus Music Corner",
    currentBid: 3100,
    minIncrement: 150,
    endsInLabel: "3d left",
    bidderCount: 3,
    status: "live",
    isWatchlisted: false,
  },
  {
    id: "auc-5",
    title: "Comic Book Collection (12 issues)",
    category: "Collectibles",
    sellerName: "Kawit Comics",
    currentBid: 900,
    minIncrement: 50,
    endsInLabel: "45m left",
    bidderCount: 8,
    status: "ending-soon",
    isWatchlisted: false,
  },
  {
    id: "auc-6",
    title: "Mountain Bike, Barely Used",
    category: "Other",
    sellerName: "General Trias Wheels",
    currentBid: 6400,
    minIncrement: 200,
    endsInLabel: "2d 9h left",
    bidderCount: 15,
    status: "live",
    isWatchlisted: true,
  },
];

export const MOCK_AUCTION_DETAILS: Record<string, AuctionDetail> = Object.fromEntries(
  MOCK_AUCTIONS.map((auction) => [
    auction.id,
    {
      ...auction,
      description: `A well-kept ${auction.title.toLowerCase()}, sold as-is. Message the seller for more photos or questions before bidding.`,
      condition: "Used — Good",
      photoCount: 4,
      bidHistory: [
        { id: `${auction.id}-bid-1`, bidderName: "J.***", amount: auction.currentBid, timeLabel: "5 min ago" },
        {
          id: `${auction.id}-bid-2`,
          bidderName: "M.***",
          amount: auction.currentBid - auction.minIncrement,
          timeLabel: "22 min ago",
        },
        {
          id: `${auction.id}-bid-3`,
          bidderName: "R.***",
          amount: auction.currentBid - auction.minIncrement * 2,
          timeLabel: "1h ago",
        },
      ],
    },
  ]),
);
